apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

#namespace: sealed-secrets
# Releases are found here https://github.com/bitnami-labs/sealed-secrets/releases
resources:
#- No resources at this level as everything comes from the environment.
#
- https://github.com/bitnami-labs/sealed-secrets/releases/download/v0.16.0/controller.yaml

